import { Test, TestingModule } from '@nestjs/testing';
import { AppController } from './app.controller';
import { GeneratorService } from './services/generator/generator.service';
import { DominoesService } from './services/dominoes/dominoes.service';
import { TableValidatorService } from './services/table-validator/table-validator.service';
import TABLE_CONSTANTS from './constants/table.const';

describe('AppController', () => {
  let appController: AppController;

  let dominoesServiceMock;
  let generatorServiceMock;
  let tableValidatorServiceMock;

  beforeEach(async () => {
    dominoesServiceMock = {
      solveProblem: jest.fn(),
    };
    generatorServiceMock = {
      generateValidData: jest.fn(),
    };
    tableValidatorServiceMock = {
      checkTable: jest.fn(),
    };
    const app: TestingModule = await Test.createTestingModule({
      controllers: [AppController],
      providers: [
        { provide: DominoesService, useValue: dominoesServiceMock },
        { provide: GeneratorService, useValue: generatorServiceMock },
        { provide: TableValidatorService, useValue: tableValidatorServiceMock },
      ],
    }).compile();

    appController = app.get<AppController>(AppController);
  });

  describe('#getHealth', () => {
    it('should return true', () => {
      expect(appController.getHealth()).toBe(true);
    });
  });

  describe('#getConditions', () => {
    it('should return TABLE_CONSTANTS', () => {
      expect(appController.getConditions()).toBe(TABLE_CONSTANTS);
    });
  });

  describe('#generate', () => {
    it('should return data, generated by GeneratorService', () => {
      const expectedValue = { numbers: [], positions: [] };
      generatorServiceMock.generateValidData.mockReturnValue(expectedValue);

      expect(appController.generate()).toEqual(expectedValue);
    });
  });

  describe('#solve', () => {
    it('should check table', () => {
      appController.solve({ initialTable: [] });
      expect(tableValidatorServiceMock.checkTable).toHaveBeenCalled();
    });

    it('should solve the problem', () => {
      const expectedSolution = [];
      dominoesServiceMock.solveProblem.mockReturnValue(expectedSolution);

      appController.solve({ initialTable: [] });

      expect(appController.solve({ initialTable: [] })).toEqual(
        expectedSolution,
      );
    });
  });
});
