import {
  Body,
  Controller,
  Get,
  HttpStatus,
  Post,
  UseFilters,
  UseInterceptors,
} from '@nestjs/common';
import { DominoesService } from './services/dominoes/dominoes.service';
import { DefaultFilter } from './filters/default.filter';
import { ErrorHandlingInterceptor } from './interceptors/error-handling.interceptor';
import { TableValidatorService } from './services/table-validator/table-validator.service';
import TABLE_CONSTANTS from './constants/table.const';
import { AutoGeneratedSolution } from './interfaces/auto-generated-solution';
import { GeneratorService } from './services/generator/generator.service';
import { InitialTableDto } from './dto/initial-table.dto';
import { TableConstantsDto } from './dto/table-constants.dto';
import { ApiResponse } from '@nestjs/swagger';

@Controller()
@UseInterceptors(ErrorHandlingInterceptor)
@UseFilters(new DefaultFilter())
export class AppController {
  constructor(
    private readonly dominoesService: DominoesService,
    private readonly tableValidatorService: TableValidatorService,
    private readonly generatorService: GeneratorService,
  ) {}

  @Get('health')
  getHealth(): boolean {
    return true;
  }

  @Get('conditions')
  getConditions(): TableConstantsDto {
    return TABLE_CONSTANTS;
  }

  @Get('generate')
  generate(): AutoGeneratedSolution {
    return this.generatorService.generateValidData();
  }

  @Post('solve')
  @ApiResponse({
    status: HttpStatus.BAD_REQUEST,
    description: 'Incorrect initial table',
  })
  solve(@Body() initialTableDto: InitialTableDto): string[][] {
    const initialTable = initialTableDto.initialTable;
    this.tableValidatorService.checkTable(initialTable);
    return this.dominoesService.solveProblem(initialTable);
  }
}
